version: '3'
services:
  python-app:
    build: .
    ports:
      - "80:8000"
    depends_on:
      - postgres

  postgres:
    image: postgres:12
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: rest_app
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 567234
