services:
  mongo:
    image: mongo:latest
    restart: always
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
      - mongo-config:/etc/mongo
      - ./init.js:/docker-entrypoint-initdb.d/init.js:ro
    env_file:
      - .env

  mongo-express:
    image: mongo-express:latest
    restart: always
    container_name: mongo-express
    ports:
      - "8081:8081"
    env_file:
      - .env
    depends_on:
      - mongo

volumes:
  mongo-data:
    driver: local
  mongo-config:
    driver: local

